src/objects/vail_test__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <formula>test_test__c + TEXT(today())</formula>
        <label>Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Url__c</fullName>
        <label>Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>link__c</fullName>
        <formula>HYPERLINK(&apos;https://chikpale-dev-ed.lightning.force.com/lightning/r/Account/&apos;&amp;Account__r.Id&amp;&apos;/view&apos;,  Account__r.Name  ,&apos;self&apos;)</formula>
        <label>link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>test_test__c</fullName>
        <label>test test</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>vail test</label>
    <nameField>
        <displayFormat>vt-{0000000}</displayFormat>
        <label>vail test Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LightningCheckClass.cls
global class LightningCheckClass {
	@AuraEnabled
	public static List<sObject> getCustomObject() { 
		List<sObject> test = [Select Name,test_test__c,Start_Date__c,End_Date__c,link__c,Key__c,Phone_Number__c,Email__c,Url__c From vail_test__c ORDER BY Name DESC limit 10];
		System.debug('test : '+test);
		return test;
	}
    
	@AuraEnabled
	public static List<vail_test__c> setCustomObject(String TestString) { 
		
		List<vail_test__c> testp = (List<vail_test__c>)JSON.deserialize(TestString, List<vail_test__c>.class);
		upsert testp;

		List<vail_test__c> test = [Select Name,test_test__c,Start_Date__c,End_Date__c,link__c,Key__c,Phone_Number__c,Email__c,Url__c From vail_test__c ORDER BY Name DESC limit 10];
		System.debug('test1 : '+test);
		return test;
	}
    
    @AuraEnabled
    public static List<vail_test__c> SearchTexts(String searchKey,String entersearch) {
        String query = 'Select Name,test_test__c,Start_Date__c,End_Date__c,link__c,Key__c,Phone_Number__c,Email__c,Url__c From vail_test__c WHERE '+searchKey+'=\''+entersearch+'\'';
        List<vail_test__c> test = Database.query(query);
        return test;
    }
}